language: generic

before_install:
- git config --global user.email "travis@travis-ci.com"
- git config --global user.name "Travis CI"

services:
- docker

script:
- docker-compose run build

deploy:
  provider: script
  script: ./scripts/deploy.sh
  cleanup: false

env:
  global:
    # GITHUB_TOKEN
  - secure: "wF5E4ktQzTKuAb5S41vCbP53mqOWGoPAodvA56NeDLT706+2qD5ZLJO+Fts4KzBahqFQ5vzRT1uGqwCk8LBVqTj3lPheSTcCtPdj1kOGj2+HiCkteCDRzhtt+GUT+SzhWrhHGRxtdFTfxw0fIGSsg+I1azo7pJ4goGfFdXjpOvX4n2aR3k9XZufZ0OdwxGEu/oRCSLYE/1RWogjqE/zs+n9Z2wATorl68AIkg+4t61AKxYIyEkX0ULqd3ML8Dgi6B6dx+sDMPujlkuTL7F+zDqydZUyL0qkGCawaJXYxf96hrupY94sPoN6YArZ9lBwsq+Ne+fnsd5KRuVuZv1bmNPYIUNkU1BdGSGuYinMFa2oKSwwQFzisuuZvGCoQYzwyxmOG75fDKwpNjZKnAV+/9BCGcGqsCALoI5++E1HIgqVN+BVuHm+2LiQpdvdfD3e646piwcVffSyrPnueciWmBWq3wKQi3lHhHiX9AFt07OzMQ56dxQXd+jQslNE5QbRuH3aRNYlNkrQgYxfRXP3ZTpzRN4ofE07eVBMebGlUUGU7+g5JziRlXYEqjCGgn0bonTKezK/30acANfvb0MfTpIHqlQEOLIz240CCIAaszIv7usdenRxcDGSbDb/Hu/Vz7IAu0YIjQFA7RK/N2CRUg8j/lugLCqAzz/qYlH0Fl0A="
