language: generic

before_install:
- git config --global user.email "travis@travis-ci.com"
- git config --global user.name "Travis CI"

services:
- docker

script:
- docker-compose run build

deploy:
  provider: script
  script: npx ts-node scripts/deploy.ts
  skip_cleanup: true
  on:
    branch: master

env:
  global:
  - GITHUB_DEPLOY_REPO: "algrx/algrx.github.io"
  # GITHUB_DEPLOY_TOKEN
  - secure: "WfzCM2lq3Pc9OtO+tR9ADbUd5yrynkaScs0r1R0Y6/S2rMAS5xsdtcdMzLmmd9wT+JwnD77aXodWOrB4UWbuuSAzhHRCZMBlk2htC6ZtuLhTfgSYHl5AqXIXGkxcXW0dh46bYU8mqtVHN6hFE/z/jHj51OmXVbLHT8Y7ukpXkycEhwzvPTYJT/DCNI0HSKsRMKhCHT9fJh0+Gxvguc6S3IRVnJ6NfPMcEuniPuZyKnaaTY8MMvW/9Q4af7Sw5sBt6LPuW+nOu9lym24iwO0Ivn1Q7MQL2Acof9EwU45j4AX6LBJRHGfljTYt5tu5oQyJj9JYy/gNlpcbMs8jkb9RKKTQP8JbI8B7cCENgiURgJzF9War9FjFUkqar69YUQpbIn5UKsVa/0SL1tH7eMXXcclxWjBa2XfBPnlkYTQieSZ6usmgrezEbBuO0iz3USYTbzF8vDfiC5DwkFnby0+hcnubMnwLqlCWSQ7nasWpZ58VgVTzuMAzpBGJ5B71msIg1P/ktP1VmU7bDbCY3BurBVZKuqZHV3jvI5kfsHozVrWkWIp3cwv4BVNldCUWTjj+HvT2/3zOm1/OqsF9G/B/J1E1TpkLKzTnLqVaJ78gfloDWxhPy6YHnwjlSVXhmVkJmVz74SHERF67uzBp32Jc06DWLHjlzIVy7VTYfdD+I54="
