version: '3.7'
services:
    build:
        build:
            context: .
            target: setup
        volumes:
            - './public:/app/public'
        image: algorithmx-website-build
        command: bash -c "
            npm run typecheck
            && npm run build"
