name: build
on: [push]

jobs:
    app:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build
              run: docker-compose up --build build

            - name: Deploy
              if: github.ref == 'refs/heads/master'
              shell: bash
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DEPLOY_GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
              run: ./scripts/deploy.sh
